# Generated by Django 3.2.13 on 2023-09-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almocos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('localizacao', models.CharField(max_length=100)),
                ('notaComida', models.FloatField()),
                ('notaPreco', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Lanches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('localizacao', models.CharField(max_length=100)),
                ('melhorLanche', models.CharField(max_length=100)),
                ('nota', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tabela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurante', models.CharField(max_length=50)),
                ('nota', models.FloatField()),
            ],
        ),
    ]
